linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocyclo
    - unparam
    - bodyclose
    - noctx

linters-settings:
  errcheck:
    check-blank: false
  gocyclo:
    min-complexity: 15

issues:
  exclude-dirs:
    - vendor
